[build]
     publish = "."
   
   [[headers]]
     for = "/*"
     [headers.values]
       X-Frame-Options = "DENY"
       X-Content-Type-Options = "nosniff"
       Cache-Control = "public, max-age=3600"
   
   [[redirects]]
     from = "/dashboard"
     to = "/index.html"
     status = 301